# -*- coding: utf-8 -*-
"""Object Detection (Spoon and Fork) with YOLO - Aisha Al Ghurabi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qEKekKSpVU4Y2HjHqzhGE4WPNXkIJCt8

#Object Detection with YOLO

## Project overview

**Objective:** In this challenge, I will explore object detection by following the Data Science Lifecycle and build a YOLO model to detect whichever two objects you choose.

## Dataset:

- Images of Spoons and Forks have been collected from different sources like Unsplash, Pexesls, Googel images, and pintrest.
- Each class had 50 images collected, so the total collected images where 100.
- The images where labeled using Roboflow and then splited into: 80% training, 10% test, and 10% for validation.
- Then the training images where augumented also in roboflow using the following settings:
  - Flip: Horizontal
  - Crop: 0% Minimum Zoom, 20% Maximum Zoom
  - Shear: ±10° Horizontal, ±10° Vertical
  - Blur: Up to 2.5px
  - Noise: Up to 1.21% of pixels

  and by this the total number of training images where 240.

### Installing the roboflow file
"""

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="xxwQ8XBX7x2ieH76Wv9W")
project = rf.workspace("aishas-workspace-hofwe").project("my-first-project-himcv")
version = project.version(2)
dataset = version.download("yolov11")

"""## Data Exploration

### Importing necessary libraries for visualization
"""

import os        # To work with files and folders
import cv2
import matplotlib.pyplot as plt
import numpy as np

# Path to training images and labels
image_folder = os.path.join("My-First-Project-2", "train/images")
label_folder = os.path.join("My-First-Project-2", "train/labels")

# Pick the first image
image_name = os.listdir(image_folder)[0]
image_path = os.path.join(image_folder, image_name)

# Corresponding label file
label_name = image_name.replace(".jpg", ".txt")
label_path = os.path.join(label_folder, label_name)

# Read the image using OpenCV
img = cv2.imread(image_path)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)  # Convert BGR to RGB

height, width, _ = img.shape

if os.path.exists(label_path):
    with open(label_path, "r") as f:
        lines = f.readlines()

    # Each line corresponds to one object
    for line in lines:
        parts = line.split()
        class_id = int(parts[0])
        polygon_coords_normalized = list(map(float, parts[1:]))

        # Reshape the list into pairs of (x, y)
        polygon_points = []
        for i in range(0, len(polygon_coords_normalized), 2):
            x_normalized = polygon_coords_normalized[i]
            y_normalized = polygon_coords_normalized[i+1]

            # Convert normalized coordinates to pixel coordinates
            x_pixel = int(x_normalized * width)
            y_pixel = int(y_normalized * height)
            polygon_points.append([x_pixel, y_pixel])

        # Convert to a numpy array for cv2.polylines
        if polygon_points:
            polygon_points = np.array(polygon_points, np.int32)
            polygon_points = polygon_points.reshape((-1, 1, 2))

            # Draw polygon on image (color green, thickness 2)
            cv2.polylines(img, [polygon_points], isClosed=True, color=(0, 255, 0), thickness=2)

# Display the image with annotations
plt.figure(figsize=(10, 10))
plt.imshow(img)
plt.axis('off')
plt.show()

"""## Model Building

### Installing Requirements (Ultralytics)

I will install the Ultralytics library to train the YOLO model.
"""

!pip install ultralytics

"""### Model Training

Parameters:
- Model architecture: yolo11s.pt
- Number of epochs: 60
- Resolution: 640x640
"""

!yolo detect train data=/content/My-First-Project-2/data.yaml model=yolo11s.pt epochs=60 imgsz=640

"""After training the best weights are saved under  runs-> detect-> train-> weights.

### Model Testing

Now I will run the model on the validation images and display the first 10 images.
"""

!yolo detect predict \
model=/content/runs/detect/train/weights/best.pt \
source=/content/My-First-Project-3/valid/images \
imgsz=640 \
save=True

import glob
from IPython.display import Image, display
for image_path in glob.glob(f'/content/runs/detect/predict/*.jpg')[:10]:
  display(Image(filename=image_path, height=400))
  print('\n')

# List all PNGs in your training folder
for img_path in glob.glob('/content/runs/detect/train/BoxP_curve.png'):
    display(Image(filename=img_path, height=400))

"""- The Precision Confidince curve shows that as confidennce increses the precision is improving.
- Espicially for spoon class where it reaches almost 1 at around 0.6 (high confidece.
- However for forks it falctuates meaning there are some false positives.
- Overall precision reaches 1 at around 0.815 which is considered very good.
"""

for img_path in glob.glob('/content/runs/detect/train/BoxPR_curve.png'):
    display(Image(filename=img_path, height=400))

"""- The light blue curve of the fork starts at high precision but it starts to drop as recall increases.
- However for the orange line representing the class of the spoon, it also started at high precisiona and stayed high even when the recall increasesd.
- Overall the model has average preformance of 0.762 across all classes which is decent.

"""

for img_path in glob.glob('/content/runs/detect/train/confusion_matrix_normalized.png'):
    display(Image(filename=img_path, height=400))

"""The Confusion Matrix shows:
- Fork class:
  - 67% of the forks where correctly classified as forks.
  - None of them where classified as spoon.
  - However 33% of them were missclassified as background.

- Spoon class:
 - 60% of the spoons where correctly classified as spoons.
 - 20 % where misscalsified as forks.
 - 20% where missclasified as background.

 - Background:
  - 75% of the background was missclassified as forks! which is very alarming.
  - The rest 25% of the background were missclassified as spoon.

## Error Analysis

The main error in this model is missclasifying the background, and also some confusion between fork and spoon class.

### Suggested improvments:
- Include images where there are no classes (fork and spoon) so the image learns when there are no classes.
- Generate more training images using additional agumentation settings.
- Another thing that may help is experementing with different yolo versions.
"""